name: Build and run functional tests using Zemu

on:
    workflow_dispatch:
    push:
        branches:
            - master
            - main
            - develop
    pull_request:
    branches:
        - main
        - develop

jobs:
    build_plugin:
        name: Build plugin using the reusable workflow
        uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
        with:
            upload_app_binaries_artifact: plugin_binaries
            flags: "DEBUG=1"

    build_develop_ethereum_app:
        name: Build Ethereum app using the reusable workflow
        uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
        with:
            app_repository: LedgerHQ/app-ethereum
            app_branch_name: develop
            flags: "DEBUG=1 CAL_TEST_KEY=1"
            upload_app_binaries_artifact: ethereum_build_develop

    ragger_tests_with_ethereum_develop:
        name: Run ragger tests using the reusable workflow
        needs:
            - build_plugin
            - build_develop_ethereum_app
        uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
        with:
            download_app_binaries_artifact: plugin_binaries
            additional_app_binaries_artifact: ethereum_build_develop
            additional_app_binaries_artifact_dir: ./tests/.test_dependencies/ethereum/build
